-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: UserAgreement.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE useragreement (
  ua_user INT NOT NULL,
  ua_user_accepted_timestamp TIMESTAMPTZ DEFAULT '1970-01-01 00:00:00+00' NOT NULL,
  PRIMARY KEY(ua_user)
);
