-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: UserAgreement.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/useragreement (
  ua_user INTEGER UNSIGNED NOT NULL,
  ua_user_accepted_timestamp BLOB DEFAULT '19700101000000' NOT NULL,
  PRIMARY KEY(ua_user)
);
